name: household_expenditure_pca
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - black=25.1.0
  - flake8=7.1.2
  - isort=6.0.0
  - loguru=0.7.2
  - pip=25.0.1
  - python==3.10.8
  - tqdm=4.67.1
  - typer=0.15.1
  - huggingface_hub=0.24.6
  - pandas=2.2.3
  - numpy=2.2.2
  - scipy=1.15.1
  - plotly=5.24.1
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - filelock=3.13.1
  - fsspec=2024.12.0
  - idna=3.7
  - ld_impl_linux-64=2.43
  - libffi=3.4.6
  - libgcc-ng=14.2.0
  - libgcc=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libsqlite=3.49.1
  - libstdcxx-ng=11.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - numexpr=2.10.1
  - numpy-base=2.2.2
  - openssl==1.1.1w
  - packaging=24.2
  - pathspec=0.12.1
  - platformdirs=4.3.6
  - pycodestyle=2.12.1
  - pyflakes=3.2.0
  - pygments=2.19.1
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - setuptools=72.1.0
  - shellingham=1.5.4
  - tenacity=9.0.0
  - tk=8.6.13
  - tomli=2.2.1
  - typer-slim-standard=0.15.1
  - typer-slim=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wheel=0.45.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - ghp-import==2.1.0
      - kiwisolver==1.4.8
      - markdown==3.7
      - matplotlib==3.10.0
      - mergedeep==1.3.4
      - mkdocs==1.6.1
      - mkdocs-get-deps==0.2.0
      - pillow==11.1.0
      - pyparsing==3.2.1
      - python-dotenv==1.0.1
      - pyyaml-env-tag==0.1
      - seaborn==0.13.2
      - six==1.17.0
      - watchdog==6.0.0
  - fastparquet
  - jupyter
