name: household_expenditure_pca
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3.2
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - black=25.1.0
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.1
  - cramjam=2.7.0
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.4
  - fastparquet=2024.11.0
  - filelock=3.13.1
  - flake8=7.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gettext=0.21.0
  - glib=2.82.2
  - glib-tools=2.82.2
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.2
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - icu=69.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - isort=6.0.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - krb5=1.20.1
  - ld_impl_linux-64=2.43
  - libclang=13.0.1
  - libedit=3.1.20230828
  - libevent=2.1.10
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.18
  - libllvm13=13.0.1
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.47
  - libpq=14.5
  - libsodium=1.0.18
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.3.1
  - loguru=0.7.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=2.0.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.74
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openssl=1.1.1w
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.12.1
  - pcre2=10.44
  - pexpect=4.8.0
  - pip=25.0.1
  - platformdirs=4.3.6
  - plotly=5.24.1
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pyflakes=3.2.0
  - pygments=2.19.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt=5.12.9
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - scipy=1.15.1
  - send2trash=1.8.2
  - setuptools=72.1.0
  - shellingham=1.5.4
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.49.1
  - stack_data=0.2.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - ghp-import==2.1.0
      - markdown==3.7
      - mergedeep==1.3.4
      - mkdocs==1.6.1
      - mkdocs-get-deps==0.2.0
      - python-dotenv==1.0.1
      - pyyaml-env-tag==0.1
      - six==1.17.0
      - watchdog==6.0.0
